// POST /api/email-plan
// Body: { email: string, plan: { workout, meal } }
// Sends the plan via Resend.
//
// Env vars required:
//   RESEND_API_KEY - from https://resend.com/api-keys
//   EMAIL_FROM     - optional; defaults to "onboarding@resend.dev" (works for
//                    testing to your OWN address). For production, verify a
//                    domain in Resend and use e.g. "Plans <plans@yourdomain.com>".

export default async function handler(req, res) {
  if (req.method !== "POST") {
    return res.status(405).json({ error: "Method not allowed. Use POST." });
  }

  const key = process.env.RESEND_API_KEY;
  if (!key) {
    return res.status(500).json({ error: "RESEND_API_KEY is not set on the server." });
  }
  const from = process.env.EMAIL_FROM || "onboarding@resend.dev";

  const body = typeof req.body === "string" ? safeParse(req.body) : (req.body || {});
  const { email, plan } = body || {};
  if (!email || !plan || !plan.workout || !plan.meal) {
    return res.status(400).json({ error: "Body must include `email` and a `plan` with workout + meal." });
  }

  try {
    const r = await fetch("https://api.resend.com/emails", {
      method: "POST",
      headers: { Authorization: `Bearer ${key}`, "Content-Type": "application/json" },
      body: JSON.stringify({
        from,
        to: email,
        subject: "Your personalized fitness plan",
        html: renderEmail(plan)
      })
    });

    if (!r.ok) {
      const detail = await r.text();
      return res.status(502).json({ error: "Resend request failed", status: r.status, detail });
    }
    const data = await r.json().catch(() => ({}));
    return res.status(200).json({ ok: true, id: data.id || null });
  } catch (e) {
    return res.status(500).json({ error: e.message });
  }
}

function safeParse(s) { try { return JSON.parse(s); } catch { return null; } }
function esc(s) {
  return String(s).replace(/[&<>"]/g, c => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;" }[c]));
}

function renderEmail(plan) {
  const w = plan.workout, m = plan.meal;
  const card = "background:#141a2e;border:1px solid #2a3350;border-radius:12px;padding:16px;margin:0 0 16px;";
  const th = "text-align:left;color:#94a3b8;font-size:12px;padding:4px 8px;";
  const td = "color:#e2e8f0;font-size:13px;padding:6px 8px;border-top:1px solid #233;";

  const workoutDays = (w.days || []).map(d => `
    <div style="${card}">
      <div style="color:#a5b4fc;font-weight:600;margin-bottom:8px;">${esc(d.day)} · ${esc(d.focus)}</div>
      <table style="width:100%;border-collapse:collapse;">
        <tr><th style="${th}">Exercise</th><th style="${th}">Sets</th><th style="${th}">Reps</th><th style="${th}">Rest</th></tr>
        ${(d.exercises || []).map(e => `<tr>
          <td style="${td}">${esc(e.name)}</td><td style="${td}">${esc(e.sets)}</td>
          <td style="${td}">${esc(e.reps)}</td><td style="${td}">${esc(e.rest)}</td></tr>`).join("")}
      </table>
    </div>`).join("");

  const mealDays = (m.days || []).map(d => `
    <div style="${card}">
      <div style="color:#6ee7b7;font-weight:600;margin-bottom:8px;">${esc(d.day)}</div>
      ${(d.meals || []).map(meal => `<div style="color:#e2e8f0;font-size:13px;padding:4px 0;">
        <b>${esc(meal.meal)}</b> — ${esc(meal.items)} <span style="color:#94a3b8;">(${esc(meal.kcal)} kcal)</span></div>`).join("")}
    </div>`).join("");

  return `<div style="background:#0b1020;padding:24px;font-family:Arial,Helvetica,sans-serif;">
    <div style="max-width:640px;margin:0 auto;">
      <h1 style="color:#fff;font-size:22px;">Your fitness plan</h1>
      <h2 style="color:#c7d2fe;font-size:16px;">Workout — ${esc(w.summary || "")}</h2>
      ${workoutDays}
      <h2 style="color:#a7f3d0;font-size:16px;">Nutrition — ${esc(m.calories)} kcal · ${esc(m.protein)}P / ${esc(m.carbs)}C / ${esc(m.fat)}F</h2>
      <p style="color:#94a3b8;font-size:13px;">${esc(m.note || "")}</p>
      ${mealDays}
      <p style="color:#475569;font-size:12px;margin-top:24px;">Generated by your Fitness Planner.</p>
    </div>
  </div>`;
}
